baseURL: https://mrobee.github.io/
languageCode: en-us
title: Robby's Log

module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod

theme:
  - github.com/adityatelange/hugo-PaperMod

disqusShortname: mrobee-github-io
googleAnalytics: G-HYYFPBCD8Y

params:
  env: production
  comments: true
